### ISSUE TITLE
[SCIPION, SAPS] Validate Infrastructure Manager deployments

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/SQAaaS#27]
This issue will track the advancements to validate via the SQAaaS both the Ansible and IM (TOSCA, RADL) recipes from these use cases:
- [x] SCIPION
- [x] SAPS

**Comment by amcaar** [comment]
SAPS RADL recipes to be used with EC3: https://github.com/ufcg-lsd/saps-docker/tree/master/ec3_recipe
Also in that repo you can find the K8s deployment files for each SAPS service.

**Comment by micafer** [comment]
Scipion TOSCA document: https://github.com/grycap/im-dashboard/blob/master/tosca-templates/scipion.yml
And inside this TOSCA document you can find the main installation recipe: https://raw.githubusercontent.com/CERIT-SC/scipion-docker/video_laura/ansible.yaml

**Comment by micafer** [comment]
Created initial test on how to test the deployment in case of using only IM:
https://github.com/EOSC-synergy/IM-test.sqaaas.

We need to inject the cloud provider credentials (IISAS offered its site) in this variable:
https://github.com/EOSC-synergy/IM-test.sqaaas/blob/master/.sqa/docker-compose.yml#L12

The user must provide the RADL or TOSCA to test here:
https://github.com/EOSC-synergy/IM-test.sqaaas/blob/master/.sqa/config.yml#L12

We can use UPV VMRC to register a base image to use it in the tests.

**Comment by orviz** [comment]
Linked to JePL https://github.com/indigo-dc/jenkins-pipeline-library/issues/164
