### ISSUE TITLE
File not found in build context error

### ISSUE THREAD

**Issue by ldelcano** [EOSC-synergy/SQAaaS#29]
I am executing a pipeline that builds a docker image from a docker file in this url:
https://github.com/CERIT-SC/scipion-docker/tree/master/worker-image
Build image works locally without errors but when trying the pipeline I get the following error:

Step 35/43 : COPY plugin-list.txt ${S_USER_HOME}/
Service 'scipion-worker' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat plugin-list.txt: file does not exist

That file is there and as I said no problems when building the image on my server, any idea why is failing in jenkins?

**Comment by orviz** [comment]
Hi @ldelcano, thanks for reporting the issue. There was indeed a bug in the code (solved in https://github.com/EOSC-synergy/sqaaas-api-server/pull/111) that did not handle appropriately the Docker build context and thus it fail to locate the required files. Could you please give a new try?

**Comment by ldelcano** [comment]
Now it passes that step.
