### ISSUE TITLE
Quality criteria box empty on Jenkins pipeline

### ISSUE THREAD

**Issue by ldelcano** [EOSC-synergy/SQAaaS#43]
I am trying to compose the same pipeline as I always do but since yesterday combox to select critieria appears empty (I noticed in the past that this happens when you are no login but I am login with EGI SSO as always).

![image](https://user-images.githubusercontent.com/12271385/143822081-c625d8df-4cac-4e18-8b27-de2aa1e5747d.png)

**Comment by orviz** [comment]
Hi @ldelcano very sorry for this unfortunate situation.., the certificates of the SQAaaS APIs have expired and we are now in the process of renewing them. Hope they can be back during today. You can check their status in:

https://status.eosc-synergy.eu/

**Comment by orviz** [comment]
@ldelcano the SQAaaS portal is finally available
