### ISSUE TITLE
Pipeline creation: Error 500 server

### ISSUE THREAD

**Issue by ldelcano** [EOSC-synergy/SQAaaS#47]
Hi, I am trying to create a new pipeline and when I get to the final step I get the following error (see screenshot).
I have tried all sort of variations but no idea on what is happening (I cannot Try it out, it is on that screen but before).

![image](https://user-images.githubusercontent.com/12271385/146886778-8790ff2b-d112-4709-9dd5-22ed9bac7832.png)

**Comment by orviz** [comment]
Linked issue https://github.com/EOSC-synergy/sqaaas-api-server/issues/149

**Comment by orviz** [comment]
Hi @ldelcano thanks for reporting this, there was actually a bug in the code, now fixed. Could you please try the same workflow again to ensure nothing else is wrong there?

**Comment by ldelcano** [comment]
It works now, thanks!
