### ISSUE TITLE
no image or build context for hadolint service

### ISSUE THREAD

**Issue by ldelcano** [EOSC-synergy/SQAaaS#48]
Hi, I am trying to run the same pipeline I have been trying for the last months but now I get a strange error that did not appear before:

+ docker-compose -f .sqa/docker-compose.yml --project-directory /jenkins/workspace/cipionCloud-worker.sqaaas_master/ down -v
The Compose file is invalid because:
Service scipion-hadolint has neither an image nor a build context specified. At least one must be provided.
This is the pipeline: https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/ScipionCloud-worker.sqaaas/job/master/15

I can see that now there is a tool hadolint but since I am not sure how to use it I am still using the COMMANDS tool as you showed in the video tutorial (it worked before, I had problems cause image is to big and timeout and other things but never complained about hadolint image before)

sorry to bother you again and merry Christmas!

**Comment by orviz** [comment]
Fixed in https://github.com/EOSC-synergy/sqaaas-api-server/pull/155

**Comment by orviz** [comment]
@ldelcano your input is really good for us, no doubt you deserve a gold badge for detecting issues! :1st_place_medal: 

Just fixed this one, so in principle you should be able to create the pipeline as usual. As you point out, `hadolint` tool is available in the dropdown list of `QC.Sty` criterion, so you can use it even without defining/providing a service for it (this is handled by SQAaaS). Hopefully the screenshot below clarifies its usage:

![image](https://user-images.githubusercontent.com/1225231/147454047-ae7f3345-667e-4f86-a948-b8fdf0b5bd56.png)

Thanks again!

**Comment by ldelcano** [comment]
Thanks Pablo, I have tried both ways and I get this error:

Using hadolint criteria without hadolint service:
https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/ScipionCloud-worker.sqaaas/job/master/18/console
+ docker-compose -f .sqa/docker-compose.yml --project-directory /jenkins/workspace/cipionCloud-worker.sqaaas_master/ exec -T scipion-worker hadolint Dockerfile --ignore SC2046 --ignore DL3002 --ignore DL3059 --ignore DL3047 --ignore SC2086 --ignore DL3027 --ignore DL3015 --ignore DL3008
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "hadolint": executable file not found in $PATH: unknown

Using commands criteria with a hadolint service:
https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/ScipionCloud-worker.sqaaas/job/master/19/console

+ docker-compose -f .sqa/docker-compose.yml --project-directory /jenkins/workspace/cipionCloud-worker.sqaaas_master/ exec -T scipion-hadolint h a d o l i n t - - i g n o r e S C 2 0 4 6 - - i g n o r e D L 3 0 0 2 - - i g n o r e D L 3 0 5 9 - - i g n o r e D L 3 0 4 7 - - i g n o r e S C 2 0 8 6 - - i g n o r e D L 3 0 2 7 - - i g n o r e D L 3 0 1 5 - - i g n o r e D L 3 0 0 8 w o r k e r - i m a g e / D o c k e r f i l e

OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "h": executable file not found in $PATH: unknown

**Comment by orviz** [comment]
In your first try you used the service `scipion-worker`, which does not contain the `hadolint` command, that's why the pipeline failed. Generally speaking, when selecting a specific tool from the dropdown list, **you are no longer asked to provide a service for running the tool** (and this statement also includes `commands`). The SQAaaS selects a Docker image for you, still we left the service selection dropdown list for those cases where you want to use your own Docker image. So in this example, you can either leave unselected the service or use a custom Docker image with the tool, such as your `scipion-hadolint`. Appreciate if you can test it again.

Regarding the second try, the failure is once again on the SQAaaS side. Just fixed this one, thanks again for reporting this!

**Comment by ldelcano** [comment]
Image is being now build. Thanks.
