### ISSUE TITLE
K8s cluster deployment at INCD

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/SQAaaS#69]

**Comment by orviz** [comment]
[JePL-k8s-test](https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/JePL-k8s-test/job/feature%252Fserviceqa/) to be working on Wed 14th

**Comment by samuelbernardolip** [comment]
Not directly related with this task, I found several issues in current Jenkins release that could address most of the problems reported.
I'm still finishing the tests for JePL-k8s-test regarding Jenkinsfile. Then I need to test with SQAaaS API and Web.

**Comment by samuelbernardolip** [comment]
The pipeline is working now, the only issue is related to the wordpress example code, since no service is being started:
https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/JePL-k8s-test/job/feature%252Fserviceqa/26/console

Maybe some environment variable needed to start the containers.

**Comment by samuelbernardolip** [comment]
Working now using credentials and with all security issues solved:
https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/JePL-k8s-test/job/feature%252Fserviceqa/31/console

Deployment is failing because of missing configuration from wordpress example side.

**Comment by samuelbernardolip** [comment]
Besides kubectl, also need to do the same test using helm chart:
https://github.com/bitnami/charts/tree/master/bitnami/wordpress

**Comment by samuelbernardolip** [comment]
kubectl deployment is failing because the pods are not being created. No issue on current configurations.
Maybe missing resources on current k8s cluster...

**Comment by samuelbernardolip** [comment]
Add test for helm chart:
https://github.com/EOSC-synergy/JePL-helm-test

With helm it gets the configuration examples from the helm chart repository and this way the code on the test repository is lighter then on the kubectl examples. It is also possible to run helm charts from local files, but that is not covered on this test.

**Comment by samuelbernardolip** [comment]
Deployment fails because helm chart tries to obtain an external IP but that is not possible because current Openstack installation don't provide Octavia module.
The deployment task is complete for kubectl and helm.
