### ISSUE TITLE
[Request for help] Add direct link to your services

### ISSUE THREAD

**Issue by geyslein** [EOSC-synergy/SQAaaS#72]
**Describe your use case.**
I want to promote your service 'Pipeline as a Service' and 'Quality Assessment and Awarding' to third parties and use a designated link for that: "Hey, look, the EOSC has sth. for you: LINK"

**Describe the problem you found.**
AFAIK, I only have the link to SQAaaS Web itself but not to the specific service.

**Comment by orviz** [comment]
Many thanks @geyslein for the suggestion, let see what we can do. We'll keep you posted

**Comment by darce-i3m** [comment]
We have implemented a login redirection so when an unlogged user tries to access to a restricted page, the web is redirected to the login, remembering where to go after user logs in.

In this way, it is possible to access directly to the services through these links:

**Pipeline as a Service** - https://sqaaas.eosc-synergy.eu/#/auth/pipeline-name
**Quality Assessment and Awarding** - https://sqaaas.eosc-synergy.eu/#/auth/full-assessment
